# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ![Welcome Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:8ff47a85-7250-4d86-8e48-2f346b48b2c1:BannerWelcome.jpg/full/750,/0/default.jpg)

  :tada: Welcome to Autistica-CitizenScience! :tada:
  We're really excited to have your input into the project! :sparkling_heart:

  <br>If you haven't done so already, please make sure you check out our [Contributing Guidelines](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/CODE_OF_CONDUCT.md).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ![Thank You Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:7fbd97cf-283b-480c-b8e1-11866e26245c:BannerThanks.jpg/full/750,/0/default.jpg)

  :sparkling_heart: Thanks for opening this pull request! :sparkling_heart:
  We really appreciates your time and effort to contribute to the project.
  Please make sure you have read our [Contributing Guidelines](https://github.com/alan-turing-institute/AutisticaCitizenScience/blob/master/CONTRIBUTING.md) and filled in our pull request template to the best of your ability.

  <br>We have Continuous Integration tests that check the writing style and will help you track down any slip-ups :recycle:
  The Netlify bot will also comment with a preview of the book with your additions so you can see how it will look once it's merged! :tada:

  <br>We sometimes get many pull requests on this repo, so please be patient and we will get back to you as soon as we can.
  If we don't acknowledge this pull request after 7 days, feel free to contact us.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ![Congratulations Banner](https://zenodo.org/api/iiif/v2/0c0188d3-d03c-4830-a6e3-00405f5c22fa:32fbdb89-ae1b-434e-830c-88ade86724cc:BannerCongratulations.jpg/full/750,/0/default.jpg)

  Congrats on merging your first pull request! :tada:
  We here at Autistica-CitizenScience really appreciate your contributions! :sparkling_heart:
  Go ahead and share your your first merge with your colleagues, you got yourself this brag right! :smile: :gift:
